### ISSUE TITLE
Get this package back into Stackage

### ISSUE THREAD

**Issue by donkeybonks** [onrock-eng/github-webhooks#29]
There's a problem in a recent update to aeson with the date parsing that causes the test suite to fail (even though there isn't a noticeable regression).

We'd be very grateful if anyone wanted to undertake this project.

**Comment by Sir4ur0n** [comment]
Hi, I just took a quick look (I came across this issue on Reddit), and this looks like the real issue is the `time` library upgrade from 1.8.x to 1.9.x. It broke some code that also used to work in the `cron` library and I fixed it back there.

E.g. with resolver `nightly-2020-07-04` the following code fails at runtime: `read "2020-02-18 00:54:04" :: UTCTime` and basically your tests heavily rely on such syntax.

Note, fixing is as simple as adding a `Z` at the end of each string to carry the timezone information.

I will open a PR shortly that should fix this.

**Comment by Sir4ur0n** [comment]
To clarify: this is a good thing that the `Read` instance of `UTCTime` now breaks on inputs such as `"2020-02-18 00:54:04"` because such a time carries no timezone information, thus it's dangerous (and may be unexpected by users) that it decides to default the timezone to UTC.
