### ISSUE TITLE
Please put on Stackage

### ISSUE THREAD

**Issue by tsani** [onrock-eng/github-webhooks#4]
Hey there! In a recent PR to [servant-github-webhook](https://github.com/tsani/servant-github-webhook/pull/8), a dependency on `github-webhooks` was introduced in order to easily support a dynamically changing set of webhook keys. Currently, we have to use the `extra-deps` field in `stack.yaml` to get it to build.

Will you be adding `github-webhooks` to Stackage soon? The links to Stackage in the readme are currently 404s.

**Comment by donkeybonks** [comment]
Hi @tsani , thanks for raising this !

github-webhooks is only a package candidate at the moment, pending further testing for the 1.0.0 release.

I would like to solve #2 and #3 before releasing so that the API remains as stable as possible for the very long foreseeable future.

Just before 1.0.0 is released on Hackage I will open the pull request to Stackage and it should all land quite quickly! ETA 2 weeks okay?

**Comment by donkeybonks** [comment]
@tsani we will be pushing back the roadmap a little bit on this. I'll update this soon with the new release dates.

**Comment by donkeybonks** [comment]
Addressed by https://github.com/fpco/stackage/pull/3322 .

**Comment by donkeybonks** [comment]
Closed by https://github.com/fpco/stackage/commit/b432dc680b5d459ae00ab60654926e5ab140fc69.
