### ISSUE TITLE
ghc-7.10 and earlier build with minimal changes, but are not supported

### ISSUE THREAD

**Issue by donkeybonks** [onrock-eng/github-webhooks#6]
Can be seen here:
https://github.com/rahulmutt/github-webhooks/commit/cf16054e2ae9eba8c3bca3e2bbe5e1fb5bffd817

@rahulmutt feel free to add a gate on the options needed for this to build and submit your fork as a pull request.

**Comment by donkeybonks** [comment]
see also https://github.com/tsani/servant-github-webhook/issues/11 .

**Comment by rahulmutt** [comment]
@donkeybonks Spent some time looking at the blame for the new warning flags and I found this:
https://github.com/ghc/ghc/commit/2206fa8cdb1209320f3690690b610320b4810de6

So essentially, `-Wincomplete-uni-patterns -Wincomplete-record-updates` can be replaced with `-fwarn-incomplete-uni-patterns -fwarn-incomplete-record-updates` to make it work for older GHC versions too. According to the commit comment:
> The old `-fwarn...`-based warning flags will remain functional for the forseeable future.

So I think doing `s/-W/-fwarn-/` is a safe option that keeps everyone happy. I don't think you should go with my forked changes since I did those in a rush and didn't check to see if there were any alternatives.
